### ISSUE TITLE
打包一条龙时，找不到FLEXArgumentInputNotSupported

### ISSUE THREAD

**Issue by sthyuhao** [yohunl/FlexInjected#1]
(Reading database ... 2765 files and directories currently installed.)
Unpacking com.yourcompany.flexinjected (from /tmp/_theos_install.deb) ...
dpkg: error processing /tmp/_theos_install.deb (--install):
 unable to create `./Library/Application Support/FLEXLoader/FLEX.framework/PrivateHeaders/FLEXArgumentInputNotSupportedView.haders/./Library/Application Support/FLEXLoader/FLEX.framework/PrivateHeaders/FLEXArgumentInputNotSupported': No such file or directory
dpkg-deb: subprocess paste killed by signal (Broken pipe: 13)
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1

**Comment by yohunl** [comment]
是不是你的theos的环境设置的问题?
